# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/basys3_demo_board/VHDL_projeleri/dot_matrix_beti_yazar/dot_matrix_beti_yazar/dot_matrix_beti_yazar.cache/wt [current_project]
set_property parent.project_path C:/basys3_demo_board/VHDL_projeleri/dot_matrix_beti_yazar/dot_matrix_beti_yazar/dot_matrix_beti_yazar.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib C:/basys3_demo_board/VHDL_projeleri/dot_matrix_beti_yazar/dot_matrix_beti_yazar/dot_matrix_beti_yazar.srcs/sources_1/new/beti_duz.vhd
read_xdc C:/basys3_demo_board/VHDL_projeleri/dot_matrix_beti_yazar/dot_matrix_beti_yazar/dot_matrix_beti_yazar.srcs/constrs_1/new/beti_duz_cons.xdc
set_property used_in_implementation false [get_files C:/basys3_demo_board/VHDL_projeleri/dot_matrix_beti_yazar/dot_matrix_beti_yazar/dot_matrix_beti_yazar.srcs/constrs_1/new/beti_duz_cons.xdc]

synth_design -top beti_duz -part xc7a35tcpg236-1
write_checkpoint -noxdef beti_duz.dcp
catch { report_utilization -file beti_duz_utilization_synth.rpt -pb beti_duz_utilization_synth.pb }
